<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="22" passed="18">
  <reporter-output>
  </reporter-output>
  <suite name="Main Test Suite" duration-ms="13993" started-at="2014-04-29T04:08:05Z" finished-at="2014-04-29T04:08:19Z">
    <groups>
    </groups>
    <test name="Main Test Group" duration-ms="13993" started-at="2014-04-29T04:08:05Z" finished-at="2014-04-29T04:08:19Z">
      <class name="qa.tests.FailTest">
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.FailTest@66d33a]" test-instance-name="682c5358" name="setName" is-config="true" duration-ms="5" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setsSuccess()[pri:0, instance:qa.tests.FailTest@66d33a]" test-instance-name="682c5358" name="setsSuccess" duration-ms="947" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setsSuccess -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.FailTest@66d33a]" test-instance-name="682c5358" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:06Z" finished-at="2014-04-28T21:08:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="FAIL" signature="showFailure()[pri:0, instance:qa.tests.FailTest@66d33a]" test-instance-name="682c5358" name="showFailure" duration-ms="1805" started-at="2014-04-28T21:08:06Z" finished-at="2014-04-28T21:08:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at qa.tests.FailTest.showFailure(FailTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- showFailure -->
      </class> <!-- qa.tests.FailTest -->
      <class name="qa.tests.BeforeTestSkip">
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.BeforeTestSkip@7cf10a6f]" test-instance-name="765099ec" name="setName" is-config="true" duration-ms="5" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="SKIP" signature="arraysFailures_3()[pri:0, instance:qa.tests.BeforeTestSkip@7cf10a6f]" test-instance-name="765099ec" name="arraysFailures_3" duration-ms="0" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_3 -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:qa.tests.BeforeTestSkip@7cf10a6f]" test-instance-name="765099ec" name="setUp" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[SkipException thrown in setUp method.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: SkipException thrown in setUp method.
	at qa.tests.BeforeTestSkip.setUp(BeforeTestSkip.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- qa.tests.BeforeTestSkip -->
      <class name="qa.tests.AssertTests1">
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="5" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_1()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="arraysFailures_1" duration-ms="1699" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ expected [[J@7651dd54] but found [[I@6b9d6ec4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  expected [[J@7651dd54] but found [[I@6b9d6ec4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertArrayEquals(Assert.java:144)
	at org.testng.Assert.assertEquals(Assert.java:117)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests1.arraysFailures_1(AssertTests1.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_1 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:07Z" finished-at="2014-04-28T21:08:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_2()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="arraysFailures_2" duration-ms="1642" started-at="2014-04-28T21:08:07Z" finished-at="2014-04-28T21:08:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [[I@4261e82f]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [[I@4261e82f]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests1.arraysFailures_2(AssertTests1.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_2 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:08Z" finished-at="2014-04-28T21:08:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_3()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="arraysFailures_3" duration-ms="1827" started-at="2014-04-28T21:08:08Z" finished-at="2014-04-28T21:08:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[J@3e6c77d9] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[J@3e6c77d9] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertArrayEquals(Assert.java:155)
	at org.testng.Assert.assertEquals(Assert.java:117)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests1.arraysFailures_3(AssertTests1.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_3 -->
        <test-method status="PASS" signature="intArray_Issue4()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="intArray_Issue4" duration-ms="571" started-at="2014-04-28T21:08:10Z" finished-at="2014-04-28T21:08:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intArray_Issue4 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:10Z" finished-at="2014-04-28T21:08:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="int_Integer_Arrays()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="int_Integer_Arrays" duration-ms="860" started-at="2014-04-28T21:08:11Z" finished-at="2014-04-28T21:08:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- int_Integer_Arrays -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:11Z" finished-at="2014-04-28T21:08:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:11Z" finished-at="2014-04-28T21:08:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="noOrderFailure()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="noOrderFailure" duration-ms="1729" started-at="2014-04-28T21:08:11Z" finished-at="2014-04-28T21:08:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Arrays not equal: [a, b, b] and [a, a, b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Arrays not equal: [a, b, b] and [a, a, b]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failAssertNoEqual(Assert.java:713)
	at org.testng.Assert.assertEqualsNoOrder(Assert.java:703)
	at org.testng.Assert.assertEqualsNoOrder(Assert.java:735)
	at qa.tests.AssertTests1.noOrderFailure(AssertTests1.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOrderFailure -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:13Z" finished-at="2014-04-28T21:08:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="noOrderSuccess()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="noOrderSuccess" duration-ms="1886" started-at="2014-04-28T21:08:13Z" finished-at="2014-04-28T21:08:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOrderSuccess -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:15Z" finished-at="2014-04-28T21:08:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setsSuccess()[pri:0, instance:qa.tests.AssertTests1@7e0babb1]" test-instance-name="a74b77e0" name="setsSuccess" duration-ms="964" started-at="2014-04-28T21:08:15Z" finished-at="2014-04-28T21:08:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setsSuccess -->
      </class> <!-- qa.tests.AssertTests1 -->
      <class name="qa.tests.SkipTest">
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="setName" is-config="true" duration-ms="5" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setsSuccess()[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="setsSuccess" duration-ms="2232" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setsSuccess -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:07Z" finished-at="2014-04-28T21:08:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="SKIP" signature="testSkipException(java.lang.String, java.lang.Integer)[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="testSkipException" duration-ms="548" started-at="2014-04-28T21:08:07Z" data-provider="dp" finished-at="2014-04-28T21:08:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Iteration1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testing SkipException effect on report output.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testing SkipException effect on report output.
	at qa.tests.SkipTest.testSkipException(SkipTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkipException -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:08Z" finished-at="2014-04-28T21:08:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="SKIP" signature="testSkipException(java.lang.String, java.lang.Integer)[pri:0, instance:qa.tests.SkipTest@2a18f23c]" test-instance-name="051a3aa5" name="testSkipException" duration-ms="765" started-at="2014-04-28T21:08:08Z" data-provider="dp" finished-at="2014-04-28T21:08:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Iteration2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[37]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Testing SkipException effect on report output.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Testing SkipException effect on report output.
	at qa.tests.SkipTest.testSkipException(SkipTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkipException -->
      </class> <!-- qa.tests.SkipTest -->
      <class name="qa.tests.AssertTests2">
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="5" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_1()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="arraysFailures_1" duration-ms="535" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ expected [[J@4b65c4dd] but found [[I@37efef9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  expected [[J@4b65c4dd] but found [[I@37efef9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertArrayEquals(Assert.java:144)
	at org.testng.Assert.assertEquals(Assert.java:117)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests2.arraysFailures_1(AssertTests2.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_1 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_2()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="arraysFailures_2" duration-ms="2416" started-at="2014-04-28T21:08:05Z" finished-at="2014-04-28T21:08:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [[I@1b0817f2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [[I@1b0817f2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests2.arraysFailures_2(AssertTests2.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_2 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:08Z" finished-at="2014-04-28T21:08:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="arraysFailures_3()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="arraysFailures_3" duration-ms="2642" started-at="2014-04-28T21:08:08Z" finished-at="2014-04-28T21:08:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[J@8a24a11] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[J@8a24a11] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertArrayEquals(Assert.java:155)
	at org.testng.Assert.assertEquals(Assert.java:117)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at qa.tests.AssertTests2.arraysFailures_3(AssertTests2.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arraysFailures_3 -->
        <test-method status="PASS" signature="intArray_Issue4()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="intArray_Issue4" duration-ms="2857" started-at="2014-04-28T21:08:10Z" finished-at="2014-04-28T21:08:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intArray_Issue4 -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="0" started-at="2014-04-28T21:08:10Z" finished-at="2014-04-28T21:08:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="4" started-at="2014-04-28T21:08:13Z" finished-at="2014-04-28T21:08:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="int_Integer_Arrays()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="int_Integer_Arrays" duration-ms="984" started-at="2014-04-28T21:08:13Z" finished-at="2014-04-28T21:08:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- int_Integer_Arrays -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:14Z" finished-at="2014-04-28T21:08:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="noOrderFailure()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="noOrderFailure" duration-ms="1077" started-at="2014-04-28T21:08:14Z" finished-at="2014-04-28T21:08:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Arrays not equal: [a, b, b] and [a, a, b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Arrays not equal: [a, b, b] and [a, a, b]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failAssertNoEqual(Assert.java:713)
	at org.testng.Assert.assertEqualsNoOrder(Assert.java:703)
	at org.testng.Assert.assertEqualsNoOrder(Assert.java:735)
	at qa.tests.AssertTests2.noOrderFailure(AssertTests2.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOrderFailure -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:15Z" finished-at="2014-04-28T21:08:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="noOrderSuccess()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="noOrderSuccess" duration-ms="1756" started-at="2014-04-28T21:08:15Z" finished-at="2014-04-28T21:08:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOrderSuccess -->
        <test-method status="PASS" signature="setName()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setName" is-config="true" duration-ms="1" started-at="2014-04-28T21:08:17Z" finished-at="2014-04-28T21:08:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setName -->
        <test-method status="PASS" signature="setsSuccess()[pri:0, instance:qa.tests.AssertTests2@45c8e616]" test-instance-name="27993da1" name="setsSuccess" duration-ms="1699" started-at="2014-04-28T21:08:17Z" finished-at="2014-04-28T21:08:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setsSuccess -->
      </class> <!-- qa.tests.AssertTests2 -->
    </test> <!-- Main Test Group -->
  </suite> <!-- Main Test Suite -->
</testng-results>
